### ISSUE TITLE
Add ability to record that a user has gained access to a software product after purchase

### ISSUE THREAD

**Issue by jcreek** [jcreek/SvelteKitSaasBoilerplate#14]
This should be able to handle both outright purchase and a subscription. A separate ticket should be created for removing access when a subscription has expired. 

An alternative and possibly better approach might be to link the user to a set of stripe transactions, which could then be used to determine when loading any given digital product whether or not they have access to it.

**Comment by OllyNicholass** [comment]
I think to achieve this, we'll want to assign two parts of metadata to the Stripe session when it's created:
`userId` (userId from supabase, or alternative authentication), `productIds` (Ids of the products from the database, not Stripe)

The products in Stripe will also need some metadata attached: `productId`

When we're handling the checkout completion (On the /checkout/success route) we'll confirm the status of payment and then we can process the items.

We can get the products from the `session.metadata.productIds`, and the user from the `session.metadata.userId`
And create the record in the DB to associate the user with the products.

**Comment by jcreek** [comment]
@OllyNicholass this video seems pertinent https://youtu.be/ag7HXbgJtuk?si=OPlZeOpX19Vo7SRK

We could just use stripe as the source of truth for whether or not they have purchased a product and should have access.

**Comment by jcreek** [comment]
@OllyNicholass I've created a branch with my attempt at these changes. Please pull it down and take a look, see what you think. I'd recommend avoiding using the local db for now, and seeing if this implementation works for the stripe webhooks you were trying before :)
