### ISSUE TITLE
Prevent buying a product you have already purchased

### ISSUE THREAD

**Issue by jcreek** [jcreek/SvelteKitSaasBoilerplate#34]

**Comment by OllyNicholass** [comment]
We have this ability within Stripe but exclusively for subscriptions.
https://docs.stripe.com/payments/checkout/limit-subscriptions

For One-time purchase products, we will need to do a DB lookup at the point of creating the stripe checkout session, comparing whether the user has previously purchased that item - which we are already recording.

Edge cases may include
- Same Customer, Multiple Payment Attempts: Ensure that if the same customer tries to initiate multiple purchases simultaneously (e.g., by opening multiple tabs), you check the purchase status at each step to prevent duplicates.
- Refunds: If a customer is refunded, you might want to allow them to repurchase the product. In this case, ensure your system updates the purchase status accordingly.

**Comment by jcreek** [comment]
I think we can do this ahead of time instead of just in time - on the product page itself we can check if they have access and if so replace the purchase button with something else saying that they have already bought it.

**Comment by jcreek** [comment]
As for refunds, I'm not sure how that works in stripe, but that would also work here as we'd just delete the entry in the purchases table, which would allow them to purchase it again.
