### ISSUE TITLE
Enable tracking usage of 'credits'

### ISSUE THREAD

**Issue by jcreek** [jcreek/SvelteKitSaasBoilerplate#37]
For example, a user buys a purchase of Open AI credits, and then these get used whenever they make an OpenAI call.

**Comment by OllyNicholass** [comment]
Assuming this will require our own credit currency to be recorded by the database.

Stripe also implements usage based subscriptions, so could potentially allow customers to set that up as an enhancement
![image](https://github.com/user-attachments/assets/2e7aa51f-b048-4557-9b42-dcf4c24f284b)
