### ISSUE TITLE
Log the error when signout fails

### ISSUE THREAD

**Issue by OllyNicholass** [jcreek/SvelteKitSaasBoilerplate#61]
- [ ] Log the error when signout fails

Method: `async function signOut(supabase: SupabaseClient, callback: () => void): Promise<void>`
File: `src\lib\utils\supabase\auth.ts`

https://github.com/jcreek/SvelteKitSaasBoilerplate/blob/8540a2c50fa862ae620ed6472c36c2809135fd8a/src/lib/utils/supabase/auth.ts#L3C1-L6C2

**Comment by jcreek** [comment]
This can be done once #66 is merged

**Comment by jcreek** [comment]
Closing this issue as not only is it a duplicate but it's no longer doable as it's an error in the client side
